FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
COPY static ./static
USER 1000:1000
EXPOSE 3500
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3500", "--proxy-headers", "--forwarded-allow-ips", "*"]
